name: Static code analysis

on: [push]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: phpqa
        uses: docker://jakzal/phpqa:php8.2-alpine
        run: phpqa
