name: Static code analysis

on: [push]

jobs:
  static-code-analysis:
    container: jakzal/phpqa:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: phpqa
        run: phpqa
