name: Static code analysis

on: [push]

jobs:
  static-code-analysis:
    container: docker://jakzal/phpqa:php8.2-alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: phpqa
        run: phpqa
